version: '2'

services:
    web:
        build: .
        ports:
         - "8080:8080"
        links:
         - db
         - broker
    broker:
        image: rabbitmq
        ports:
         - "5672:5672"
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: apptrack
            POSTGRES_DB: apptrackdb
            POSTGRES_USER: apptrackrole
