version: '2'

services:
    web:
        build:
            dockerfile: Dockerfile
            context: hobbyServer
        links:
         - db
         - broker
    broker:
        image: rabbitmq
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: apptrack
            POSTGRES_USER: apptrack
