export const userConstants = {
    SOCKET_CONNECT_START: 'SOCKET_CONNECT_START',
    SOCKET_CONNECT_SUCCESS: 'SOCKET_CONNECT_SUCCESS',
    SOCKET_CONNECT_SERVER_MESSAGE: 'SOCKET_CONNECT_SERVER_MESSAGE',
    SOCKET_CONNECT_CLIENT_MESSAGE: 'SOCKET_CONNECT_CLIENT_MESSAGE',
    SOCKET_CONNECT_CLIENT_ERROR: 'SOCKET_CONNECT_CLIENT_ERROR',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    INFO_REQUEST: 'USERS_INFO_REQUEST',
    INFO_SUCCESS: 'USERS_INFO_SUCCESS',
    INFO_FAILURE: 'USERS_INFO_FAILURE',

    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',
};
